### ISSUE TITLE
fiware service issue for device command

### ISSUE THREAD

**Issue by achandana** [telefonicaid/iotagent-json#532] opened 2021-02-26 07:05 UTC
We are facing issue like if we create the device in fiware service is starting with capital letter command not registering with Orion. 

We have created device like below:

Device Provisioning :
curl --location --request POST 'http://localhost:4041/iot/devices' \
--header '**fiware-service: IoTPlatform**' \
--header 'fiware-servicepath: /' \
--header 'Content-Type: application/json' \
--data-raw '{
"devices": [
{
"device_id": "lamp001",
"entity_name": "urn:ngsi-ld:Lamp:001",
"entity_type": "Lamp",
"transport": "MQTT",
**"commands": [
{"name": "on","type": "command"},
{"name": "off","type": "command"}
],**
"attributes": [
{"object_id": "s", "name": "state", "type":"Text"},
{"object_id": "l", "name": "luminosity", "type":"Integer"}
]
}
]
}'
Entity in Orion:
curl --location --request GET 'http://localhost:1026/v2/entities/urn:ngsi-ld:Lamp:001' \
--header 'fiware-service: IoTPlatform' \
--header 'fiware-servicepath: /'

{
    "id": "urn:ngsi-ld:Lamp:001",
    "type": "Lamp",
    "TimeInstant": {
        "type": "DateTimeWithMilis",
        "value": "2021-02-26T06:08:43.960Z",
        "metadata": {}
    },
    "luminosity": {
        "type": "Integer",
        "value": " ",
        "metadata": {}
    },
    **"off_info": {
        "type": "commandResult",
        "value": " ",
        "metadata": {}
    },
    "off_status": {
        "type": "commandStatus",
        "value": "UNKNOWN",
        "metadata": {}
    },
    "on_info": {
        "type": "commandResult",
        "value": " ",
        "metadata": {}
    },
    "on_status": {
        "type": "commandStatus",
        "value": "UNKNOWN",
        "metadata": {}
    }**,
    "state": {
        "type": "Text",
        "value": " ",
        "metadata": {}
    }
}

There is no 'on' and 'off' attributes created in the Orion.

 if we create the device in fiware service is starting with small letter command is registering with Orion.

curl --location --request POST 'http://localhost:4041/iot/devices' \
--header '**fiware-service: **iotplatform****' \
--header 'fiware-servicepath: /' \
--header 'Content-Type: application/json' \
--data-raw '{
"devices": [
{
"device_id": "lamp002",
"entity_name": "urn:ngsi-ld:Lamp:002",
"entity_type": "Lamp",
"transport": "MQTT",
"commands": [
{"name": "on","type": "command"},
{"name": "off","type": "command"}
],
"attributes": [
{"object_id": "s", "name": "state", "type":"Text"},
{"object_id": "l", "name": "luminosity", "type":"Integer"}
]
}
]
}'

Entity in Orion:
curl --location --request GET 'http://localhost:1026/v2/entities/urn:ngsi-ld:Lamp:002' \
--header 'fiware-service: iotplatform' \
--header 'fiware-servicepath: /'

{
    "id": "urn:ngsi-ld:Lamp:002",
    "type": "Lamp",
    "TimeInstant": {
        "type": "DateTimeWithMilis",
        "value": "2021-02-26T06:14:09.907Z",
        "metadata": {}
    },
    "luminosity": {
        "type": "Integer",
        "value": " ",
        "metadata": {}
    },
    "off_info": {
        "type": "commandResult",
        "value": " ",
        "metadata": {}
    },
    "off_status": {
        "type": "commandStatus",
        "value": "UNKNOWN",
        "metadata": {}
    },
    "on_info": {
        "type": "commandResult",
        "value": " ",
        "metadata": {}
    },
    "on_status": {
        "type": "commandStatus",
        "value": "UNKNOWN",
        "metadata": {}
    },
    "state": {
        "type": "Text",
        "value": " ",
        "metadata": {}
    },
    **"on": {
        "type": "command",
        "value": "",
        "metadata": {}
    },
    "off": {
        "type": "command",
        "value": "",
        "metadata": {}
    }**
}

Can anyone please help us with suggestion and what would be the fix for this. We want command should support the capital letter fiware-service as well.

**Comment by AlvaroVega** [comment] 2021-04-22 09:51
I've trying these curls and I've see:
- Device registrations are fine,
- MongoDB collections about device collections and entity collections contains the same values in both cases
- The difference appreciated is related with ContextBroker (maybe API.?)
Maybe this issue should be moved to ContextBrokker repository, what do you think @fgalan ?

**Comment by fgalan** [comment] 2021-04-27 09:26
Related issue: https://github.com/telefonicaid/iotagent-node-lib/issues/1023

**Comment by fgalan** [comment] 2021-04-27 12:10
> Can anyone please help us with suggestion and what would be the fix for this. We want command should support the capital letter fiware-service as well.

From https://thinking-cities.readthedocs.io/en/latest/multitenancy/index.html (with defines service and service path for all componentes in the platform, including CB, IOTAs, etc.), regarding **service**

> If uppercase characters are used, they are converted to lowercase.

Are you tests showing a different behaviour?

As side note, note this is differnt from **service path**

> It is interpreted in a case-sensitive way.

**Comment by fgalan** [comment] 2021-04-27 12:35
I have done the following test.

A device is created using this curl command:

```
curl --location --request POST 'http://localhost:4061/iot/devices' --header 'fiware-service: myservice' --header 'fiware-servicepath: /' --header 'Content-Type: application/json' -d @- << EOF
{
"devices": [
{
"device_id": "lamp001",
"entity_name": "urn:ngsi-ld:Lamp:001",
"entity_type": "Lamp",
"transport": "MQTT",
"commands": [
{"name": "on","type": "command"},
{"name": "off","type": "command"}
],
"attributes": [
{"object_id": "s", "name": "state", "type":"Text"},
{"object_id": "l", "name": "luminosity", "type":"Integer"}
]
}
]
}
EOF
```

That creates `orion-myservice` DB. In addition, it creates the following document in the `iotaul` database:

```
{
        "_id" : ObjectId("6088000ee7b0ebadfc001e36"),
        "active" : [
                {
                        "object_id" : "s",
                        "name" : "state",
                        "type" : "Text"
                },
                {
                        "object_id" : "l",
                        "name" : "luminosity",
                        "type" : "Integer"
                }
        ],
        "commands" : [
                {
                        "name" : "on",
                        "type" : "command",
                        "object_id" : "on"
                },
                {
                        "name" : "off",
                        "type" : "command",
                        "object_id" : "off"
                }
        ],
        "staticAttributes" : [ ],
        "subscriptions" : [ ],
        "creationDate" : ISODate("2021-04-27T12:14:06.376Z"),
        "id" : "lamp001",
        "type" : "Lamp",
        "name" : "urn:ngsi-ld:Lamp:001",
        "service" : "MyService",
        "subservice" : "/",
        "registrationId" : "6088000ecc2a8f61d42f09ae",
        "internalId" : null,
        "protocol" : "IoTA-UL",
        "transport" : "MQTT",
        "explicitAttrs" : false,
        "__v" : 0
}
```

Note the `"service": "MyService"` field (due to https://github.com/telefonicaid/iotagent-node-lib/issues/1023, I guess):

Now, if I do the following query on Orion:

```
curl --location --request GET 'http://localhost:10026/v2/entities/urn:ngsi-ld:Lamp:001' --header 'fiware-service: MyService' --header 'fiware-servicepath: /'
```

I get the response reported in the issue above (i.e. `on` and `off` are not there) and the following WARN and ERROR traces in the logs:

```
time=2021-04-27T12:24:30.603Z | lvl=WARN | corr=842395d0-a753-11eb-8a16-0242ac11001b; cbfwd=1 | trans=1619497978-230-00000000310 | from=172.17.0.1 | srv=myservice | subsrv=/ | comp=Orion | op=httpRequestSend.cpp[583]:httpRequestSendWithCurl | msg=Notification response NOT OK, http code: 404
time=2021-04-27T12:24:30.603Z | lvl=WARN | corr=842395d0-a753-11eb-8a16-0242ac11001b; cbfwd=1 | trans=1619497978-230-00000000310 | from=172.17.0.1 | srv=myservice | subsrv=/ | comp=Orion | op=AlarmManager.cpp[405]:badInput | msg=Raising alarm BadInput 172.17.0.1: JSON Parse Error
time=2021-04-27T12:24:30.603Z | lvl=WARN | corr=842395d0-a753-11eb-8a16-0242ac11001b; cbfwd=1 | trans=1619497978-230-00000000310 | from=172.17.0.1 | srv=myservice | subsrv=/ | comp=Orion | op=postQueryContext.cpp[369]:queryForward | msg=Internal Error (error parsing reply from context provider: Errors found in incoming JSON buffer)
```

It seems that Orion is forwarding the request but IOTA is responding with a 404 not found error. This probably because due to https://github.com/telefonicaid/iotagent-node-lib/issues/1023 for the IOTA is not the same `myservice` than `MyService` so causing the 404 response. Due to this 404, Orion is not including `on` or `off` in the response to the client.

---------

Let's test same case, but using `myservice` instead of `MyService` and provision time. From `orion-myservice` perspective, nothing changes but in the device document at IOTA DB we see now `"service" : "myservice"`.

Now the GET query on Orion works and shows `on` and `off` attributes. No WARN or ERROR trace is seen at the log (thus meaning that the forwarding took place and the IOTA answers with a 200 OK).

-------

My conclusion is that when https://github.com/telefonicaid/iotagent-node-lib/issues/1023 gets solved this issue will be also solved.

**Comment by fgalan** [comment] 2021-04-27 12:38
Side note regarding:

> I get the response reported in the issue above (i.e. `on` and `off` are not there)

The problem is not that `on` or `off` command are not in the response to a `GET /v2/entities`. These "virtual attributes" are aimed at invoking commands, i.e. its value in a `GET` response is meaningless (the important info is the attributes suffixed by `_info` and `_status`.

The real problem is that when you would try to invoke a command (e.g. `PUT /v2/entities/urn:ngsi-ld:Lamp:001/attrs/on?type=Lamp`) the forwarding will also fail due to this issue.

**Comment by fgalan** [comment] 2021-04-27 12:41
Of course, the temporal workaround to this issue is to use always service names in lowercase. In fact, it is a good practice (mixing uppercase and lowercase relying on that the platform will convert to lowercase it isn't a good idea ;)

**Comment by fgalan** [comment] 2021-04-30 08:42
After merging https://github.com/telefonicaid/iotagent-node-lib/issues/1023 this issue should be fixed.

@achandana could you test (using `:latest` version in IOTA at Dockerhub) and tell us how it goes, please? Thanks!

**Comment by Keshav-NEC** [comment] 2023-08-02 18:09
Hi @fgalan , I think this issue can be closed.

**Comment by fgalan** [comment] 2023-08-03 11:21
Ok, let's close it. We could reopen it in the case @achandana test is and found some further problem.

**Closed by fgalan** 2023-08-03 11:21 UTC
