### ISSUE TITLE
Add a second Dockerfile for Automated Builds

### ISSUE THREAD

**Issue by jason-fox** [telefonicaid/iotagent-json#342] opened 2018-10-31 13:51 UTC
@dcalvoalonso @fgalan - Something for discussion, can we offer two docker files in the repo to improve the user experience?

## Current situation

The Docker image for each of the IoT Agents is a **public automated build**. This means that:

1) The description of the Image comes from the `README` in the same directory as the `Dockerfile` 
2) The `latest` image will be built every time a commit occurs - i.e. `latest` is bleeding edge development

## What is the issue

There are two problems with this.

1) The full description is currently a copy of the GitHub readme, which is not very useful for users and contains broken links, random HTML etc: https://hub.docker.com/r/fiware/iotagent-json/

2) The `latest` tag is very unstable and potentially broken, untested etc (yes I know using `latest` is bad practice)

## What I think needs to be done:

Since you can't use `COPY` from the parent directory, the current `Dockerfile` must lie in root. However there are three standard methods for getting source in a release. You can use `COPY`, `git clone` or `wget` a zip file. `git clone` is overkill for a slim release build, but `wget` of a labelled release can be easily used  to get stable source code.

I have recently fixed this in the Tutorials : https://github.com/Fiware/tutorials.Step-by-Step as follows:

The **root** contains the equivalent of the existing set-up for developers to play with:
*  a file called `Dockerfile-sample` .  - this loads the source code using a `COPY . <destination>` command
*  a `.dockerignore` file - this filters out the unnecessary files

This is effectively just a developer's hacker file - you can make changes, rebuild or try different base images.

There is a separate subdirectory called docker which holds two more files:

*  a file called `Dockerfile` .  - this is almost a duplicate of the above, but  it obtains the latest Release from GitHub using `wget` 
*  a `README` file - this forms the Full description for the Automated build. - A useful **Docker Hub** `README` would be something like - https://fiware-iotagent-json.readthedocs.io/en/latest/installationguide/index.html#configuration-with-environment-variables

This is the only file called `Dockerfile` in the whole repository and hence the one used for the automated builds.

## What is the difference?

The difference between the two `Dockerfiles` is as shown:

###  Dummy `Dockerfile-sample` in ROOT

```docker 
COPY <source> <destination> 
```

### Actual `Dockerfile`  with the `README`

```docker
RUN RELEASE=$(curl -s https://api.github.com/repos/${OWNER}/${REPOSITORY}/releases/latest | grep 'tag_name' | cut -d\" -f4) && \
  	echo ${RELEASE}  && \
  	wget --no-check-certificate -O source.zip https://github.com/${OWNER}/${REPOSITORY}/archive/${RELEASE}.zip && \
	unzip source.zip && \
	mv ${REPOSITORY}-${RELEASE}/<source> <destination> 
```

To download a labelled release instead.
(actually if you wanted to keep pushing the bleeding edge you could just replace `${RELEASE}` with `master`

### Bonus track:

Since `${OWNER}` and `${REPOSITORY}` are `ENV` variables you can

```console
docker exec <my-image-name> env
```

To find out where the source of the image comes from.

**Comment by fgalan** [comment] 2018-11-19 08:31
> The full description is currently a copy of the GitHub readme, which is not very useful for users and contains broken links, random HTML etc: https://hub.docker.com/r/fiware/iotagent-json/

Not fully sure, but I think dockerhub let to set an specific text as Full Description instead of using the repository README.md automatically. The problem is that if this text has to be modified, the modification has to be done in dockerhub manually. However, this text is pretty stable so it is not a big issue and the solution is feasible. The text could be keep in the repostory in a separate file for reference.

> The `latest` tag is very unstable and potentially broken, untested etc (yes I know using latest is bad practice)

People have always stable releases available using the specific IOTAs versions. I don't see any problem here... Or maybe I'm missing something and I don't understand the problem :)

**Comment by jason-fox** [comment] 2018-11-19 15:00
> Not fully sure, but I think dockerhub let to set an specific text as Full Description instead of using the repository README.md automatically. 

I don't think this is the case, AFAIK for Automatic builds DockerHub will always overwrite with the text from the`README.md` in the same directory as the `Dockerfile`, so we'd need to manually alter or revert to the correct text after each push. This is why at a minimum the following should be done:

```
├── README.md . <- readme for GitHub
   └── docker
       ├── Dockerfile
       └── README.md <- readme for DockerHub 
```

> Or maybe I'm missing something 

Actually its more likely I'm not being clear about what I am advocating.

It all comes down to what is the most appropriate meaning of `latest` for users. What do we want to signal? I would have thought that it would be less confusing if `latest`  pointed to the **latest stable release** rather than the **latest githash** on master

Not that I'm encouraging misuse of `latest`, but  if the `Dockerfile` is always using `wget` to download the source of versioned release then I could try to see if the latest release worked for me by omitting the version number.

As it is, omitting a version number will get whichever random patches have landed on `master` recently  (which should have undergone testing admittedly) but are less likely to have undergone QA than a  solid release with a version number.

**Comment by fgalan** [comment] 2018-11-19 15:47
I think we have two (interrelated :) topics here: one related with **where Dockerfile should be located** and other related on **how to identify the last stable version**.

With regards to **Dockerfile**, the approach of using a separate directory for Dockerfile has been used in some repository (at least in https://github.com/telefonicaid/fiware-orion/tree/master/docker, maybe in some other). It solves the problem of having a README.md different to the one in the repo root to be shown as Full Description in Dockerhub. However, it has an important drawbacks: the usual method of getting the coce with COPY command cannot be used in this case (as far as I remember).

With regards to **last stable version**, using "latest" label for that would have some implications from backward compatibility point of view, given it would imply to redefine the semantics of an already used label. Instead of that, I'd recomment to define a new tag, e.g. "stable".

In fact, note RTD already uses the labels "latest" and "stable" (although not sure if exactly with the same semantics I'm proposing)

![imagen](https://user-images.githubusercontent.com/1534240/48717072-f6df4e00-ec18-11e8-9e7f-d982ce945ff8.png)

**Comment by jason-fox** [comment] 2018-11-20 08:32
> . However, it has an important drawbacks: the usual method of getting the code with COPY command cannot be used in this case (as far as I remember).

Correct, you can't use `COPY` to retrieve from the parent directory, however, `COPY` is not the only _"standard"_ method (or semi-standard method) for getting the code.

To `wget` the **bleeding edge development** code a.k.a `latest`:

```docker
RUN RELEASE=master && \
	wget --no-check-certificate -O source.zip https://github.com/${OWNER}/${REPOSITORY}/archive/${RELEASE}.zip && \
	unzip source.zip && \
	mv ${REPOSITORY}-${RELEASE}/<source> <destination> 
```

To `wget` the latest **released version** code a.k.a `stable`:

```docker
RUN RELEASE=$(curl -s https://api.github.com/repos/${OWNER}/${REPOSITORY}/releases/latest | grep 'tag_name' | cut -d\" -f4) && \
	wget --no-check-certificate -O source.zip https://github.com/${OWNER}/${REPOSITORY}/archive/${RELEASE}.zip && \
	unzip source.zip && \
	mv ${REPOSITORY}-${RELEASE}/<source> <destination> 
```

I have also seen `Dockerfile` examples obtain the codebase using any/all of the following:

- `curl` <= same method as `wget` from GitHub archive
- `curl`/`wget` a linux `*.deb` distribution
- Download using `git clone` <=  This is usually not necessary, installing Git is overkill.
- Move the `Dockerfile`(s) to a separate repo.

I also like your idea of distinguishing `latest` and `stable` in the same manner as RTD - so I'll update the proposal accordingly:

- A "hacker's" `Dockerfile  in root can be used to `COPY` the code   
- A `docker/README.md`  holds useful info for DockerHub
- the default `docker/Dockerfile` should build latest **bleeding edge development** (for automated builds)
- **Stretch Goal** - the default `docker/Dockerfile`  with an `ARG` could build `stable` (maybe) - I guess it would be simple enough to combine the options under an `ARG`
- The install documentation must be expanded to explain the various options -  I've recently put in a PR on the [PEP Proxy](https://github.com/ging/fiware-pep-proxy/pull/64/commits/0e53e6698e1be21c310237719ef091a3de3b44df) to do something similar

**Comment by dcalvoalonso** [comment] 2018-11-20 09:57
Although I understand the proposal from @jason-fox , in this case, I would prefer to maintain things as simple as possible and to keep having a single Dockerfile.
To sum up my point of view: I would follow https://github.com/telefonicaid/iotagent-json/issues/342#issuecomment-440186820 with the exception of having the `Dockerfile-sample` file. I guess that any developers willing to play with IOTAs would clone the corresponding repository or in the worst case would be able to generate his own Docker image.

**Comment by jason-fox** [comment] 2018-11-20 10:53
To misquote [Groucho Marx](https://www.goodreads.com/quotes/1185-those-are-my-principles-and-if-you-don-t-like-them-well),  _this is my proposal, and if you don't like it, I have others_

If you don't want a separate `Dockerfile-sample` file, we could drop the idea, and: 

- annotate the real `Dockerfile`  with sufficient information to explain how to make the switch between `wget` and `COPY` methods when using a local "hacker's `Dockerfile` 
- Add text to the documentation to explain what needs to be done.

The essential if the `Dockerfile-sample` idea is dropped, is that a semi-useless `.dockerignore` **must** remain in root to ignore the `node_modules` otherwise a hacker palying with a local  `COPY` -based `Dockerfile` will get any `node_modules`  from any local instance they had on their machine  `npm install` won't overwrite them and you may get library issues.

**Comment by dcalvoalonso** [comment] 2018-11-20 10:56
I would opt for this [latest solution](https://github.com/telefonicaid/iotagent-json/issues/342#issuecomment-440231150) @jason-fox

**Comment by fgalan** [comment] 2018-12-05 15:59
Fixed by PR https://github.com/telefonicaid/iotagent-json/pull/351 in this repository. Related PRs, doing the same but in other agents are:

https://github.com/telefonicaid/iotagent-ul/pull/310
https://github.com/telefonicaid/lightweightm2m-iotagent/pull/147

**Closed** 2018-12-05 15:59 UTC
